server:
  port: 8888    # Config Server가 수신 대기하는 포트

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:C:/Users/NRholic/IdeaProjects/config/src/main/resources/config/vendor

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true