server:
  port: 8888    # Config Server가 수신 대기하는 포트

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/holicker/config/
          searchPaths: vendor

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true